name: 🐛 Bug Report
description: Create a report to help us improve WORPEN
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: When I tried to run the math operation...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Worpen Version
      options:
        - v1.0.0
        - Nightly/Main
        - Other (specify in description)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Route YAML (Reproduction)
      description: Paste the YAML route that causes the issue.
      render: yaml
      placeholder: |
        path: /api/bug
        method: POST
        logic:
          - !Set ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Server Logs
      description: Paste relevant terminal output/panics here.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Rust version, etc.
      placeholder: |
        OS: Windows 11
        Rust: 1.75.0
        Worpen: main branch
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
